[project]
name = "ai-learning"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "HaiXuan Wu", email = "whx1978938887@student.gdufe.edu.cn" }
]
requires-python = ">=3.11"
dependencies = []

[project.scripts]
ai-learning = "ai_learning:main"

[build-system]
requires = ["uv_build>=0.12.16,<0.13.0"]
build-backend = "uv_build"
